/** @deprecated Import from `@/lib/lenses/lensHelper` instead. Re-exports for transition. */
export {
  LENS_IDS,
  LENSES,
  LENS_LABELS,
  LENS_META,
  TOURIST_TYPES,
  INVEST_TYPES,
  NOTE_TOURIST_CATEGORIES,
  NOTE_INVEST_CATEGORIES,
  NOTE_TOURIST_TYPES,
  lensesFor,
  matchesActiveLens,
  lensesForOverlayLayer,
  parseLensId,
  lensFor,
  groupByLens,
  lensInputFromWikiNote,
  lensInputFromCountryNote,
  lensInputFromGeoProperties,
  lensInputFromSearchEntry,
  type LensId,
  type FocusLens,
  type LensInput,
  type LensItem,
} from "@/lib/lenses/lensHelper";
